server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.user}:${mongodb.password}@mongodb.database:27017/hello-world