apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-world.fullname" . }}
  namespace: {{.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "hello-world.name" . }}
    helm.sh/chart: {{ include "hello-world.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mongodb-user: cm9vdA==
  mongodb-password: UGE2OTYxVzByZAo=